# For Unicorn Engine. AUTO-GENERATED FILE, DO NOT EDIT [cheri_const.py]
UC_CHERI_PERM_GLOBAL = 1
UC_CHERI_PERM_EXECUTIVE = 2
UC_CHERI_PERM_MUTABLE_LOAD = 64
UC_CHERI_PERM_SETCID = 128
UC_CHERI_PERM_BRANCH_SEALED_PAIR = 256
UC_CHERI_PERM_CINVOKE = 256
UC_CHERI_PERM_SYSTEM = 512
UC_CHERI_PERM_ACCESS_SYS_REGS = 512
UC_CHERI_PERM_UNSEAL = 1024
UC_CHERI_PERM_SEAL = 2048
UC_CHERI_PERM_STORE_LOCAL = 4096
UC_CHERI_PERM_STORE_CAP = 8192
UC_CHERI_PERM_LOAD_CAP = 16384
UC_CHERI_PERM_EXECUTE = 32768
UC_CHERI_PERM_STORE = 65536
UC_CHERI_PERM_LOAD = 131072
UC_CHERI_PERMS_ALL = 262143

UC_CHERI_UPERMS_ALL = 0

UC_CHERI_OTYPE_UNSEALED = 0
UC_CHERI_OTYPE_SENTRY = 1
UC_CHERI_OTYPE_LOAD_PAIR_BRANCH = 2
UC_CHERI_OTYPE_LOAD_BRANCH = 3
